# version: '3.6'
services:
  flask-dev:
    image: flask-dev
    volumes:
    - ./app:/app
    ports:
    - "8080:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: /app/app.py
      TEMPLATES_AUTO_RELOAD: 1